## DMEPOS-Only Beneficiary Demograhics

The purpose of this notebook is to extract and store beneficiary data from the DMEPOS-by-Supplier datasets. Further cleaning and exploratory data analysis will be performed in the coming days.

End result:

Saved the dataset to the shared team directory: /dsa/groups/casestudycf25/team02/DMEPOS_Bene_only_suplr.csv

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
for f in Path("/dsa/groups/casestudycf25/team02/").iterdir():
    print(f.name)

DMEPOS_suplr_2021.csv
Medicare_Monthly_Enrollment_Jun_2025.csv
DMEPOS_suplr_2022.csv
DMEPOS_suplr_2023.csv
DMEPOS_Supplier_Service_2021.csv
DMEPOS_Supplier_Service_2022.csv
DMEPOS_Supplier_Service_2023.csv
LEIE_OIG_Exclusion_List.csv
mup_dme_ry25_p05_v10_dy21_rfrhpr.csv
mup_dme_ry25_p05_v10_dy21_rfrr.csv
mup_dme_ry25_p05_v10_dy22_rfrhpr.csv
mup_dme_ry25_p05_v10_dy22_rfrr.csv
mup_dme_ry25_p05_v10_dy23_rfrhpr.csv
mup_dme_ry25_p05_v10_dy23_rfrr.csv
RUCA2010zipcode.csv
Taxonomy Code List Dec 2023.csv
leie_with_null_npi_clean.csv
leie_with_valid_npi_clean.csv
medicare_enrollment_clean.csv
CMS_General_Payments_2021_2023_raw.csv
casestudycf25t02.sqlite.db
DMEPOS_Bene_only_suplr.csv
DMEPOS_rfrhpr_clean.csv
DMEPOS_rfrr_clean.csv
DMEPOS_cleaned_serv.csv
DMEPOS_cleaned_grouping.csv
OWNRSHP_PGYR2021_2023.csv
ownership_payment_clean.csv
DMEPOS_rfrhpr_clean_labeled.csv
DMEPOS_rfrr_clean_labeled.csv
general_payments_manufacturers_clean.csv
general_payments_providers_clean.csv
general_payments-sliced_clean.csv
general_payments_products_clean.csv
specialty_crosswalk_gpt_backfill.csv
one_specialty_per_npi.csv
DMEPOS_Amount_Stats_labeled.csv
unified_dataset.csv
DMEPOS_cleaned_suplr.csv
cms_general_payments_clean.csv
DMEPOS_cleaned_suplr_serv.csv
DMEPOS_RefPro_Ser_nar_clean.csv

In [100]:
#Loading the data
df21 = pd.read_csv("/dsa/groups/casestudycf25/team02/DMEPOS_suplr_2021.csv",na_values=["NA"])
df22 = pd.read_csv("/dsa/groups/casestudycf25/team02/DMEPOS_suplr_2022.csv",na_values=["NA"])
df23 = pd.read_csv("/dsa/groups/casestudycf25/team02/DMEPOS_suplr_2023.csv",na_values=["NA"])

In [101]:
#First few from rows from 2021 dataset
df21.head()

shape: (5, 93)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Suplr_NPI ┆ Suplr_Prv ┆ Suplr_Prv ┆ Suplr_Prv ┆ … ┆ Bene_CC_P ┆ Bene_CC_P ┆ Bene_CC_P ┆ Bene_Avg │
│ ---       ┆ dr_Last_N ┆ dr_First_ ┆ dr_MI     ┆   ┆ H_Parkins ┆ H_Arthrit ┆ H_Stroke_ ┆ _Risk_Sc │
│ i64       ┆ ame_Org   ┆ Name      ┆ ---       ┆   ┆ on_V2_Pct ┆ is_V2_Pct ┆ TIA_V2_Pc ┆ re       │
│           ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ t         ┆ ---      │
│           ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆ f64       ┆ ---       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 100300039 ┆ Reconstru ┆ null      ┆ null      ┆ … ┆ null      ┆ 0.676724  ┆ 0.094828  ┆ 0.98241  │
│ 9         ┆ ctive     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Hand To   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Shoulde…  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 100300225 ┆ Walgreen  ┆ null      ┆ null      ┆ … ┆ null      ┆ 0.272727  ┆ null      ┆ 1.500596 │
│ 4         ┆ Co.       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 100300490 ┆ Texas     ┆ null      ┆ null      ┆ … ┆ null      ┆ 0.571429  ┆ null      ┆ 2.327878 │
│ 4         ┆ Road Old  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Bridge    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Llc       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 100300493 ┆ Cvs State ┆ null      ┆ null      ┆ … ┆ null      ┆ 0.363636  ┆ null      ┆ 1.693562 │
│ 8         ┆ Capital,  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ L.L.C.    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 100300738 ┆ The Giant ┆ null      ┆ null      ┆ … ┆ 0.0       ┆ 0.342105  ┆ null      ┆ 1.188676 │
│ 6         ┆ Company,  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Llc       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [102]:
#First few from rows from 2022 dataset
df22.head()

shape: (5, 93)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Suplr_NPI ┆ Suplr_Prv ┆ Suplr_Prv ┆ Suplr_Prv ┆ … ┆ Bene_CC_P ┆ Bene_CC_P ┆ Bene_CC_P ┆ Bene_Avg │
│ ---       ┆ dr_Last_N ┆ dr_First_ ┆ dr_MI     ┆   ┆ H_Parkins ┆ H_Arthrit ┆ H_Stroke_ ┆ _Risk_Sc │
│ i64       ┆ ame_Org   ┆ Name      ┆ ---       ┆   ┆ on_V2_Pct ┆ is_V2_Pct ┆ TIA_V2_Pc ┆ re       │
│           ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ t         ┆ ---      │
│           ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆ f64       ┆ ---       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 100300039 ┆ Reconstru ┆ null      ┆ null      ┆ … ┆ null      ┆ 0.648889  ┆ null      ┆ 0.886236 │
│ 9         ┆ ctive     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Hand To   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Shoulde…  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 100300225 ┆ Walgreen  ┆ null      ┆ null      ┆ … ┆ 0.0       ┆ 0.4       ┆ null      ┆ 1.678905 │
│ 4         ┆ Co.       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 100300490 ┆ Texas     ┆ null      ┆ null      ┆ … ┆ null      ┆ 0.666667  ┆ null      ┆ 2.357026 │
│ 4         ┆ Road Old  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Bridge    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Llc       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 100300493 ┆ Cvs State ┆ null      ┆ null      ┆ … ┆ null      ┆ 0.387755  ┆ null      ┆ 1.175749 │
│ 8         ┆ Capital,  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ L.L.C.    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 100300738 ┆ The Giant ┆ null      ┆ null      ┆ … ┆ 0.0       ┆ 0.416667  ┆ null      ┆ 1.37351  │
│ 6         ┆ Company,  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Llc       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [103]:
#First few from rows from 2022 dataset
df23.head()

shape: (5, 93)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Suplr_NPI ┆ Suplr_Prv ┆ Suplr_Prv ┆ Suplr_Prv ┆ … ┆ Bene_CC_P ┆ Bene_CC_P ┆ Bene_CC_P ┆ Bene_Avg │
│ ---       ┆ dr_Last_N ┆ dr_First_ ┆ dr_MI     ┆   ┆ H_Parkins ┆ H_Arthrit ┆ H_Stroke_ ┆ _Risk_Sc │
│ i64       ┆ ame_Org   ┆ Name      ┆ ---       ┆   ┆ on_V2_Pct ┆ is_V2_Pct ┆ TIA_V2_Pc ┆ re       │
│           ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ t         ┆ ---      │
│           ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆ f64       ┆ ---       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 100300039 ┆ Reconstru ┆ null      ┆ null      ┆ … ┆ null      ┆ 0.663317  ┆ null      ┆ 1.016809 │
│ 9         ┆ ctive     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Hand To   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Shoulde…  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 100300225 ┆ Walgreen  ┆ null      ┆ null      ┆ … ┆ 0.0       ┆ 0.34      ┆ null      ┆ 1.873065 │
│ 4         ┆ Co        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 100300490 ┆ Texas     ┆ null      ┆ null      ┆ … ┆ 0.0       ┆ null      ┆ 0.0       ┆ 1.091812 │
│ 4         ┆ Road Old  ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│           ┆ Bridge    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Llc       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 100300493 ┆ Cvs State ┆ null      ┆ null      ┆ … ┆ 0.0       ┆ 0.4       ┆ null      ┆ 1.546691 │
│ 8         ┆ Capital,  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ L.L.C.    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 100300738 ┆ The Giant ┆ null      ┆ null      ┆ … ┆ null      ┆ 0.510638  ┆ null      ┆ 1.329664 │
│ 6         ┆ Company,  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Llc       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [104]:
#Quick Carpentry

#Adding a year column and combining the three different datasets
df21['Year'] = 2021
df22['Year'] = 2022
df23['Year'] = 2023


df21 = df21[['Year'] + [c for c in df21.columns if c != 'Year']]
df22 = df22[['Year'] + [c for c in df22.columns if c != 'Year']]
df23 = df23[['Year'] + [c for c in df23.columns if c != 'Year']]


df = pd.concat([df21, df22, df23], ignore_index=True)

In [105]:
#Selecting only the required attributes
only_att = ['Year', 'Suplr_NPI', 'Bene_Avg_Age', 'Bene_Feml_Cnt', 'Bene_Male_Cnt', 'Bene_Race_Wht_Cnt', 'Bene_Race_Black_Cnt', 'Bene_Race_Api_Cnt', 'Bene_Race_Hspnc_Cnt', 'Bene_Race_Natind_Cnt', 'Bene_Race_Othr_Cnt', 'Bene_Ndual_Cnt', 'Bene_Dual_Cnt','Bene_CC_BH_ADHD_OthCD_V1_Pct', 'Bene_CC_BH_Alcohol_Drug_V1_Pct', 'Bene_CC_BH_Tobacco_V1_Pct', 'Bene_CC_BH_Alz_NonAlzdem_V2_Pct', 'Bene_CC_BH_Anxiety_V1_Pct', 'Bene_CC_BH_Bipolar_V1_Pct', 'Bene_CC_BH_Mood_V2_Pct', 'Bene_CC_BH_Depress_V1_Pct', 'Bene_CC_BH_PD_V1_Pct', 'Bene_CC_BH_PTSD_V1_Pct', 'Bene_CC_BH_Schizo_OthPsy_V1_Pct', 'Bene_CC_PH_Asthma_V2_Pct', 'Bene_CC_PH_Afib_V2_Pct', 'Bene_CC_PH_Cancer6_V2_Pct', 'Bene_CC_PH_CKD_V2_Pct', 'Bene_CC_PH_COPD_V2_Pct', 'Bene_CC_PH_Diabetes_V2_Pct', 'Bene_CC_PH_HF_NonIHD_V2_Pct', 'Bene_CC_PH_Hyperlipidemia_V2_Pct', 'Bene_CC_PH_Hypertension_V2_Pct', 'Bene_CC_PH_IschemicHeart_V2_Pct', 'Bene_CC_PH_Osteoporosis_V2_Pct', 'Bene_CC_PH_Parkinson_V2_Pct', 'Bene_CC_PH_Arthritis_V2_Pct', 'Bene_CC_PH_Stroke_TIA_V2_Pct','Bene_Avg_Risk_Scre']

In [106]:
#Storing dataset with only the above selected attributes
df = df[only_att]
df.head()

shape: (5, 39)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Year ┆ Suplr_NPI  ┆ Bene_Avg_A ┆ Bene_Feml_ ┆ … ┆ Bene_CC_PH ┆ Bene_CC_P ┆ Bene_CC_P ┆ Bene_Avg_ │
│ ---  ┆ ---        ┆ ge         ┆ Cnt        ┆   ┆ _Parkinson ┆ H_Arthrit ┆ H_Stroke_ ┆ Risk_Scre │
│ i32  ┆ i64        ┆ ---        ┆ ---        ┆   ┆ _V2_Pct    ┆ is_V2_Pct ┆ TIA_V2_Pc ┆ ---       │
│      ┆            ┆ f64        ┆ i64        ┆   ┆ ---        ┆ ---       ┆ t         ┆ f64       │
│      ┆            ┆            ┆            ┆   ┆ f64        ┆ f64       ┆ ---       ┆           │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆ f64       ┆           │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2021 ┆ 1003000399 ┆ 72.919149  ┆ 163        ┆ … ┆ null       ┆ 0.676724  ┆ 0.094828  ┆ 0.98241   │
│ 2021 ┆ 1003002254 ┆ 71.058824  ┆ 32         ┆ … ┆ null       ┆ 0.272727  ┆ null      ┆ 1.500596  │
│ 2021 ┆ 1003004904 ┆ 74.692308  ┆ null       ┆ … ┆ null       ┆ 0.571429  ┆ null      ┆ 2.327878  │
│ 2021 ┆ 1003004938 ┆ 67.707692  ┆ 42         ┆ … ┆ null       ┆ 0.363636  ┆ null      ┆ 1.693562  │
│ 2021 ┆ 1003007386 ┆ 71.547619  ┆ 22         ┆ … ┆ 0.0        ┆ 0.342105  ┆ null      ┆ 1.188676  │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [107]:
#Total number of male beneficiaries 
tot = df['Bene_Male_Cnt'].sum()

In [108]:
print(tot)

14424583

In [109]:
#Column names
df.columns

['Year',
 'Suplr_NPI',
 'Bene_Avg_Age',
 'Bene_Feml_Cnt',
 'Bene_Male_Cnt',
 'Bene_Race_Wht_Cnt',
 'Bene_Race_Black_Cnt',
 'Bene_Race_Api_Cnt',
 'Bene_Race_Hspnc_Cnt',
 'Bene_Race_Natind_Cnt',
 'Bene_Race_Othr_Cnt',
 'Bene_Ndual_Cnt',
 'Bene_Dual_Cnt',
 'Bene_CC_BH_ADHD_OthCD_V1_Pct',
 'Bene_CC_BH_Alcohol_Drug_V1_Pct',
 'Bene_CC_BH_Tobacco_V1_Pct',
 'Bene_CC_BH_Alz_NonAlzdem_V2_Pct',
 'Bene_CC_BH_Anxiety_V1_Pct',
 'Bene_CC_BH_Bipolar_V1_Pct',
 'Bene_CC_BH_Mood_V2_Pct',
 'Bene_CC_BH_Depress_V1_Pct',
 'Bene_CC_BH_PD_V1_Pct',
 'Bene_CC_BH_PTSD_V1_Pct',
 'Bene_CC_BH_Schizo_OthPsy_V1_Pct',
 'Bene_CC_PH_Asthma_V2_Pct',
 'Bene_CC_PH_Afib_V2_Pct',
 'Bene_CC_PH_Cancer6_V2_Pct',
 'Bene_CC_PH_CKD_V2_Pct',
 'Bene_CC_PH_COPD_V2_Pct',
 'Bene_CC_PH_Diabetes_V2_Pct',
 'Bene_CC_PH_HF_NonIHD_V2_Pct',
 'Bene_CC_PH_Hyperlipidemia_V2_Pct',
 'Bene_CC_PH_Hypertension_V2_Pct',
 'Bene_CC_PH_IschemicHeart_V2_Pct',
 'Bene_CC_PH_Osteoporosis_V2_Pct',
 'Bene_CC_PH_Parkinson_V2_Pct',
 'Bene_CC_PH_Arthritis_V2_Pct',
 'Bene_CC_PH_Stroke_TIA_V2_Pct',
 'Bene_Avg_Risk_Scre']

In [110]:
#Saving file
df.write_csv("/dsa/groups/casestudycf25/team02/DMEPOS_Bene_only_suplr.csv")