# DMEPOS by Referring Provider & Service validation

This notebook documents the procedures for determining the structure of the DMEPOS by Referring Provider and Service dataset. We determine that the data fields `Rfrg_NPI`, `HCPCS_CD`, `Suplr_Rentl_Ind`, and `Year` compose a candidate key. We also interrogate further dependencies to determine how the dataset can be reduced for efficient storage.

In [1]:
import pandas as pd

df = pd.read_csv('/dsa/groups/casestudycf25/team02/DMEPOS_rfrhpr_clean.csv',dtype={'Rfrg_Prvdr_State_FIPS':str,'Rfrg_Prvdr_Zip5':str}) # ensure Rfrg_Prvdr_State_FIPS & Rfrg_Prvdr_Zip5 are imported as str

pd.set_option('display.max_columns', None)
df.head()

## Find a primary key

In [2]:
# check that Rfrg_NPI, HCPCS_CD, and Year form a joint key
# they don't you also need to include Suplr_Rentl_Ind
# get number of rows
nrows_orig = df.shape[0]

df_grouped = df.groupby(["Rfrg_NPI","HCPCS_CD","Suplr_Rentl_Ind","Year"])[["Tot_Suplr_Benes"]].count()

nrows_grouped = df_grouped.shape[0]

print(f'Original: {nrows_orig}, Grouped: {nrows_grouped}')
display(nrows_orig == nrows_grouped)

Original: 4413118, Grouped: 4413118

True

pd.set_option('display.max_rows', None)
df_grouped[df_grouped.Tot_Suplr_Benes > 1]

df[(df.Rfrg_NPI == 1003008715) & (df.HCPCS_CD == 'E2103') & (df.Year == 2023)]

## Interrogate further dependencies

In [3]:
# does RBCS_Id depend on HCPCS_CD?
pd.set_option('display.max_rows', None)
df_rbcs = df[["RBCS_Id","HCPCS_CD"]].groupby("HCPCS_CD").nunique()
df_rbcs[df_rbcs.RBCS_Id > 1]
# no a substantial of HCPCS_CDs correspond to 2 RBCS_Id

          RBCS_Id  HCPCS_CD
HCPCS_CD
A4221           2         1
A4224           2         1
A4225           2         1
A4259           2         1
A5500           2         1
A5501           2         1
A5504           2         1
A5512           2         1
A5513           2         1
A5514           2         1
A6010           2         1
A6011           2         1
A6021           2         1
A6022           2         1
A6023           2         1
A6154           2         1
A6196           2         1
A6197           2         1
A6198           2         1
A6199           2         1
A6203           2         1
A6204           2         1
A6206           2         1
A6207           2         1
A6208           2         1
A6209           2         1
A6210           2         1
A6211           2         1
A6212           2         1
A6213           2         1
A6214           2         1
A6215           2         1
A6216           2         1
A6217           2         1
A6218           2         1
A6219           2         1
A6220           2         1
A6222           2         1
A6223           2         1
A6224           2         1
A6231           2         1
A6233           2         1
A6234           2         1
A6235           2         1
A6236           2         1
A6237           2         1
A6238           2         1
A6240           2         1
A6242           2         1
A6243           2         1
A6244           2         1
A6245           2         1
A6248           2         1
A6251           2         1
A6252           2         1
A6253           2         1
A6254           2         1
A6255           2         1
A6257           2         1
A6258           2         1
A6259           2         1
A6261           2         1
A6266           2         1
A6402           2         1
A6403           2         1
A6407           2         1
A6441           2         1
A6442           2         1
A6443           2         1
A6444           2         1
A6445           2         1
A6446           2         1
A6447           2         1
A6448           2         1
A6449           2         1
A6450           2         1
A6451           2         1
A6452           2         1
A6453           2         1
A6454           2         1
A6455           2         1
A6456           2         1
A6457           2         1
A6550           2         1
E0424           2         1
E0431           2         1
E0951           2         1
E0952           2         1
E1016           2         1
J1554           2         1
J1817           2         1
J8600           2         1
J8610           2         1
K0738           2         1
L2200           2         1
L2210           2         1
L2220           2         1
L2232           2         1
L2270           2         1
L2275           2         1
L2280           2         1
L2330           2         1
L2340           2         1
L2385           2         1
L2390           2         1
L2395           2         1
L2397           2         1
L2492           2         1
L2795           2         1
L2810           2         1
L2820           2         1
L3000           2         1
L3020           2         1
L3030           2         1
L3031           2         1
L3040           2         1
L3100           2         1
L3170           2         1
L3300           2         1
L3332           2         1
L3540           2         1
L3580           2         1
L4350           2         1
L4386           2         1
L4387           2         1
L4396           2         1
L4397           2         1
L8400           2         1
L8440           2         1
L8470           2         1

df_rbcs.RBCS_Id.max()

In [4]:
# can we drop Suplr_Rentl_Ind and replace HCPCS_CD by RBCS_Id?
# No
nrows_orig = df.shape[0]

df_grouped = df.groupby(["Rfrg_NPI","RBCS_Id","Year"])[["Tot_Suplr_Benes"]].count()

nrows_grouped = df_grouped.shape[0]

print(f'Original: {nrows_orig}, Grouped: {nrows_grouped}')
display(nrows_orig == nrows_grouped)

Original: 4413118, Grouped: 2312819

False

We found a substantial quantity of HCPCS codes associated with two RBCS codes and confirmed the relationship was not an artifact of whether the service equipment was rented.

In [5]:
# RBCS_Id determines RBCS_Lvl & RBCS_Desc?
# Yes
pd.set_option('display.max_rows', None)
df_rbcs = df[["RBCS_Id","RBCS_Lvl","RBCS_Desc"]].groupby("RBCS_Id").nunique()
df_rbcs[(df_rbcs.RBCS_Lvl > 1) | (df_rbcs.RBCS_Desc > 1)]

Empty DataFrame
Columns: [RBCS_Id, RBCS_Lvl, RBCS_Desc]
Index: []

However, all data fields prefixed by "RBCS" are determined by the `RBCS_Id` field.

In [ ]:
# all Rfrg fields determined by Rfrg_NPI?

# no

df_rfrg = df.iloc[:,0:19].groupby("Rfrg_NPI").nunique()
df_rfrg[(df_rfrg > 1).any(axis=1)]

In [ ]:
# how about Rfrg_NPI & Year?

# yes

cols = list(df.columns[:19])
cols.append(df.columns[-1])

# print(cols)

df_rfrg = df[cols].groupby(["Rfrg_NPI","Year"]).nunique()
df_rfrg[(df_rfrg > 1).any(axis=1)]

We determined that fields prefixed by "Rfrg" are dependent on both `Rfrg_NPI` and `Year`; that is, referring provider attributes associated with a particular NPI number are subject to change from year to year.

In [ ]:
# check zip code dependencies
# some zip codes cross multiple cities, states, FIPS codes, and map to more than one RUCA
df_zip = df.iloc[:,8:15].groupby("Rfrg_Prvdr_Zip5").nunique()
df_zip[(df_zip > 1).any(axis=1)]

We observe that none of cities, states, FIPS codes, nor RUCA are entirely determined by zip code; that is, there are zip codes crossing city and state boundaries and occupying multiple RUCA designations.